### ISSUE TITLE
Make the build fail if the compile fails

### ISSUE THREAD

**Issue by t-oster** [peteruithoven/Firmware-builder#1]
It works fine on Linux (at least Mint 17.1), if you use bash.
But, if I change the main.cpp to some garbage and then do the build, I get:

```
Checking Docker
[ok] Docker is available
[ok] emptied ./bin
[note] execute build.sh inside docker container
> Building LaosLaser
Building project LASER (LPC1768, GCC_ARM)
Compile: main.cpp
[Error] main.cpp@92: In function 'int main()': 'someNotExistingMethod' was not declared in this scope
[ERROR] /home/Firmware/mbed/libraries/tests/net/protocols/laser/main.cpp: In function 'int main()':
/home/Firmware/mbed/libraries/tests/net/protocols/laser/main.cpp:92:25: error: 'someNotExistingMethod' was not declared in this scope
   someNotExistingMethod(); 
                         ^

[ok] Build successful
> copying bin to bin folder
> complete
[ok] new built files are copied succesfully
[ok] done.
```

So it thinks the build is successful even if the compile step produces an error.
